### ISSUE TITLE
fatal error: cuda_runtime_api.h: No such file or directory

### ISSUE THREAD

**Issue by mindmapper15** [espnet/warp-ctc#13]
I was building warp-ctc included in ESPNet package.
All is going well then I got this error.

building 'warpctc_pytorch._warp_ctc' extension
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/src
gcc -pthread -B /mls/john/espnet/tools/venv/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/mls/john/espnet/tools/warp-ctc/include -I/mls/john/espnet/tools/venv/lib/python3.7/site-packages/torch/lib/include -I/mls/john/espnet/tools/venv/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/mls/john/espnet/tools/venv/lib/python3.7/site-packages/torch/lib/include/TH -I/mls/john/espnet/tools/venv/lib/python3.7/site-packages/torch/lib/include/THC -I/usr/local/cuda/bin/include -I/mls/john/espnet/tools/venv/include/python3.7m -c src/binding.cpp -o build/temp.linux-x86_64-3.7/src/binding.o -std=c++11 -fPIC -DWARPCTC_ENABLE_GPU -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_warp_ctc -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /mls/john/espnet/tools/venv/lib/python3.7/site-packages/torch/lib/include/ATen/cuda/CUDAContext.h:5:0,
                 from src/binding.cpp:9:
/mls/john/espnet/tools/venv/lib/python3.7/site-packages/torch/lib/include/ATen/cuda/CUDAStream.h:6:30: fatal error: cuda_runtime_api.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1
make: *** [warp-ctc.done] Error 1

Even though cuda_runtime_api.h file can be found in its directory, Warp-CTC couldn't find it.

Luckly, I solved this error based on methods from URL below.

https://blog.csdn.net/idwtwt/article/details/98602951

Please, fix this problem as fast as you can.

**Comment by mindmapper15** [comment]
OS : CentOS 7.5 64bit
GCC Version : 5.4.0
CUDA Toolkit Version : 10.0

**Comment by sw005320** [comment]
I think adding `extra_compile_args = ['-std=c++11', '-fPIC','-I/usr/local/cuda/include']` may not be the best option because cuda may not be installed there in some systems. Did you follow https://github.com/espnet/espnet#installation ? This issue can be solved with `export CFLAGS="-I$CUDAROOT/include $CFLAGS"`, but maybe I'm wrong. @ysk24ok, what do you think?

**Comment by ysk24ok** [comment]
You may set wrong value to `CUDA_HOME`. It seems `gcc` is executed with `-I/usr/local/cuda/bin/include`  option, but it must be `-I/usr/local/cuda/include`. 
`torch.utils.cpp_extension.CUDAExtension` automatically adds `$CUDA_HOME/include` path when compiling an extension (see [torch/utils/cpp_extension.py#L516](https://github.com/pytorch/pytorch/blob/v1.1.0/torch/utils/cpp_extension.py#L516) ).
I guess `/usr/local/cuda/bin` is set to `CUDA_HOME` by mistake.

**Comment by mindmapper15** [comment]
@ysk24ok @sw005320 
You were right. I just copied and used .bashrc file from my colleague and I found CUDA_HOME set with wrong value and CFLAGS was not set.
After I changed CUDA_HOME and added CFLAGS, problem solved!
