### ISSUE TITLE
Python 3.5 build

### ISSUE THREAD

**Issue by divanikus** [espnet/warp-ctc#20]
Hello folks

Debian 9 has Python 3.5.3 in it's core system. Since Debian 9 should be still pretty common, could you please build 3.5 to pypi too?

**Comment by divanikus** [comment]
Btw, since you have your pypi token right in the repo, everyone is able to upload the built artifacts on your behalf. That's a major security problem.

**Comment by sw005320** [comment]
Thanks. Yes, it's worth to prepare it (but we did not do it because ESPnet does not support python 3.5). @ysk24ok, could you do it?

**Comment by ysk24ok** [comment]
@sw005320 I'll deal with this. But before that, we have to encrypt .pypirc token referring to https://docs.travis-ci.com/user/encryption-keys. I've deleted current token.

**Comment by ysk24ok** [comment]
[Now that Python 3.5 hits EOL](https://pythoninsider.blogspot.com/2020/10/python-35-is-no-longer-supported.html), I think we no longer need to build wheels for Python 3.5.
Let me close this issue.
