### ISSUE TITLE
Installation error with cpuonly

### ISSUE THREAD

**Issue by lnalborczyk** [espnet/warp-ctc#34]
Hi, I am trying to install `warpctc-pytorch` as part of `ESPnet` (following the install guide [here](https://espnet.github.io/espnet/installation.html)).

However, I can not install `warpctc-pytorch` on my machine... when I am trying to build `ESPnet` with `make`, I get the following error:

```
expr: syntax error
Perform on CPU mode: CPU_ONLY=0
PYTHON=/Users/Ladislas/anaconda3/bin/python3
PYTHON_VERSION=Python 3.7.6
IS_CONDA=0
USE_PIP=0
TH_VERSION=1.4.0
CONDA_PYTORCH=pytorch=1.4.0 cpuonly
PIP_PYTORCH=torch==1.4.0 -f https://download.pytorch.org/whl/cpu/torch_stable.html
CHAINER_VERSION=6.0.0
PIP_CHAINER=chainer==6.0.0
NO_CUPY=0
. ./activate_python.sh && { command -v cmake || conda install -y cmake; }
/usr/local/bin/cmake
touch cmake.done
. ./activate_python.sh && { command -v flac || conda install -y libflac -c conda-forge; }
/usr/local/bin/flac
touch flac.done
. ./activate_python.sh && { command -v ffmpeg || conda install -y ffmpeg -c conda-forge; }
/usr/local/bin/ffmpeg
touch ffmpeg.done
. ./activate_python.sh && { command -v sox || conda install -y sox -c conda-forge; }
/usr/local/bin/sox
touch sox.done
. ./activate_python.sh && { python3 -c "from ctypes.util import find_library as F; assert F('sndfile') is not None" || conda install -y libsndfile=1.0.28 -c conda-forge; }
touch sndfile.done
touch conda_packages.done
. ./activate_python.sh && ./installers/install_warp-ctc.sh
cuda_version=
ERROR: Could not find a version that satisfies the requirement warpctc-pytorch==0.2.1+torch14.cpu (from versions: none)
ERROR: No matching distribution found for warpctc-pytorch==0.2.1+torch14.cpu
make: *** [warp-ctc.done] Error 1
```

When I try to manually install `warpctc-pytorch`, I also get this error:

`python3 -m pip install warpctc-pytorch==0.2.1+torch16.cpu
`
```
ERROR: Could not find a version that satisfies the requirement warpctc-pytorch==0.2.1+torch16.cpu (from versions: none)
ERROR: No matching distribution found for warpctc-pytorch==0.2.1+torch16.cpu
```

I understand that the version I am trying to install does not exist... but how can I install `warpctc-pytorch` for a CPU-only usage?

Thank you in advance.

Ladislas

**Comment by kamo-naoyuki** [comment]
Your environment is MacOSX? MaxOSX is not supported.
Write your environment more.

**Comment by lnalborczyk** [comment]
Thank you for your prompt answer.

Yes it is MacOSX (Catalina v10.15.4). Does it mean I can not install/use `ESPnet`?

What do you mean by "write your environment more"?

**Comment by kamo-naoyuki** [comment]
It's general caution at github.

Then, you can't install espnet using the Makefile.

**Comment by lnalborczyk** [comment]
Well, as said above, I also tried to install `warp-ctc` directly (i.e., not using the Makefile) using `python3 -m pip install warpctc-pytorch==0.2.1+torch16.cpu`, which does not seem to work...

**Comment by kamo-naoyuki** [comment]
See warpctc-pytorch at pypi. It's not distributed for mac.
Try install manually.
