### ISSUE TITLE
Reorganize branch structure

### ISSUE THREAD

**Issue by ysk24ok** [espnet/warp-ctc#8]
Current branch structure is as follows,

- `pytorch_binding` (default branch, for PyTorch 0.4)
- `pytorch-1.0.0` for PyTorch 1.0
- many other WIP branches

I think branches should be reorganized. One idea is like this,

```
      *---* pytorch-0.4 branch
     /
*---*---*---*---*---*---* default branch
             \       \
              \       *---* pytorch-1.1 branch
               \
                * pytorch-1.0 branch
```

In this new branch structure, we work on the default branch (BTW we may rename `pytorch_binding` branch, because it's redundant.) to make it adapt to new PyTorch version.
When we finish the work and the code works with new PyTorch version, we checkout the new branch (e.x. `pytorch-X.Y`).
After checkout `pytorch-X.Y` branch, we do nothing on that branch except a bug. In that case a hotfix commit will be added on top of that branch.

To change current branch structure into this new structure, we will follow these steps:

1. Run `git checkout -b pytorch-0.4` at `pytorch-binding` branch

```console
$ git checkout pytorch_binding
$ git checkout -b pytorch-0.4
```

2. Update [tools/Makefile](https://github.com/espnet/espnet/blob/master/tools/Makefile) of espnet to run `git checkout -b pytorch-0.4 remotes/origin/pytorch-0.4` when `TH_VERSION` is 0.4

3. After 2 is merged and new version (v0.6.0?) of espnet is released, merge `pytorch-1.0.0` into default branch. This merge breaks backward compatibility because older version of espnet builds warp-ctc for PyTorch0.4.0 at default branch.

4. After 3, I'll work at default branch to adapt to newer version of PyTorch.

If this proposal is valid, I want maintainers to do 1. After that, I'll create a pull request for 2. We have to wait for new release to do 3, so until then I'll work on `pytorch-1.0.0` instead of default branch to make wheels for PyTorch 1.0.

Would you please check this issue @sw005320 @jnishi ?

**Comment by sw005320** [comment]
This sounds very cool idea. I fully agree with you. Please go ahead :)

**Comment by ysk24ok** [comment]
Could you run the following command and push `pytorch-0.4`  branch to `espnet/warp-ctc` repository? 

```
$ git checkout pytorch_binding
$ git checkout -b pytorch-0.4
$ git push upstream pytorch-0.4
```

I don't have an access right to push a branch.

**Comment by jnishi** [comment]
LGTM!

**Comment by ysk24ok** [comment]
Now that https://github.com/espnet/espnet/pull/1196 is merged and new version (v0.5.3) is released, I have 3 proposals. I'm glad if @sw005320 and @jnishi would check these proposals.

1. How about merging `pytorch-1.0.0` branch into `pytorch_bindings` branch (as being written above)?  This merge can be  fast-forward and cause no conflicts. After the merge, `pytorch-1.0.0` branch is no longer needed so I'm going to delete it.

2. According to @jnishi,  `pytorch-1.1` branch can work with PyTorch 1.1, but it becomes stale. Why not deleting `pytorch-1.1`, adding a commit for PyTorch 1.1 on top of `pytorch_bindings`  branch and checkout new `pytorch-1.1` branch? The fix we should add is just one line change like this.

```diff
$ git diff
diff --git a/pytorch_binding/src/binding.cpp b/pytorch_binding/src/binding.cpp
index 3bb1de8..bc5bd56 100644
--- a/pytorch_binding/src/binding.cpp
+++ b/pytorch_binding/src/binding.cpp
@@ -7,7 +7,7 @@

 #ifdef WARPCTC_ENABLE_GPU
        #include "ATen/cuda/CUDAContext.h"
-       #include "ATen/cuda/CUDAGuard.h"
+       #include "c10/cuda/CUDAGuard.h"
        #include "ATen/cuda/CUDAEvent.h"

     #include "THC.h"
```

3. I want to delete unnecessary branches for ease of maintainence. Do we still need these?

- pytorch-1.0.0-1
- pytorch-1.0.0-gcc-6
- pytorch-1.1-1
- pytorch-1.1-gcc6

**Comment by sw005320** [comment]
I fully agree with all of your ideas.
Note that we are thinking of using pytorch 1.2 in near future https://github.com/espnet/espnet/issues/1194

**Comment by jnishi** [comment]
I also agree with you.

> 3.
Sure. They are copy of working branches of my repository, and all of them are deprecated.

**Comment by ysk24ok** [comment]
I have finished 1 (merging `pytorch-1.0.0` branch into `pytorch_bindings` branch and deleting `pytorch-1.0.0`) and 3 (deleting deprecated branches).

> Note that we are thinking of using pytorch 1.2 in near future espnet/espnet#1194

You mean ESPnet does not require warp-ctc wheel for PyTorch 1.1 ?
But it takes little time and effort, so I'm going to finish 2.

**Comment by sw005320** [comment]
> You mean ESPnet does not require warp-ctc wheel for PyTorch 1.1 ?
> But it takes little time and effort, so I'm going to finish 2.

This change would not be soon and your contribution is still very valuable.
Thanks a lot for your efforts!

**Comment by ysk24ok** [comment]
Now I've finished 2 (creating new `pytorch-1.0` branch).
Currently there are only 4 branches:

- `pytorch_bindings` 
- `pytorch-0.4`
- `pytorch-1.0`
- `pytorch-1.1` 

and wheels for both PyTorch 1.0 and 1.1 are served at PyPI.
Very simplified! Let me close this issue.
